---

services:
  app:
      build:
        context: "."
        dockerfile: ./docker/Dockerfile.dev.gpu
      shm_size: '8gb'  # Shared memory size
      user: vscode
      volumes:
        - .:/workspace
      command: >
        /bin/sh -c "
          cd /workspace/project &&
          rye sync &&
          echo '=== Running Crawler for ROS2 ===' &&
          rye run python -m crawlers.ros2 &&
          echo '=== Running Feature Engineering Pipeline ===' &&
          rye run python -m pipelines.feature_engineering &&
          echo '=== Running Gradio App ===' &&
          rye run python -m app
        "
      depends_on:
        - mongodb
        - qdrant
      ports:
        - "7860:7860"
      environment:
        - GRADIO_SERVER_NAME=localhost
        - GRADIO_SERVER_PORT=7860
        - CLEARML_API_HOST=http://localhost:8008
        - CLEARML_WEB_HOST=http://localhost:8080
        - CLEARML_FILES_HOST=http://localhost:8081
        - CLEARML_API_ACCESS_KEY=generate_access_key_here
        - CLEARML_API_SECRET_KEY=generate_secret_key_here
      network_mode: "host"
    
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  mongo_data:
  qdrant_data:
